import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Locale = 'fr' | 'en' | 'de' | 'zh' | 'ja';

interface LanguageContextValue {
  locale: Locale;
  setLocale: (l: Locale) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);
const STORAGE_KEY = 'appLocale';

const STRINGS: Record<Locale, Record<string, string>> = {
  fr: {
    tabs_home: 'Accueil',
    tabs_add: 'Publier',
    tabs_profile: 'Profil',
    header_home: 'Cuisino',
    header_add: 'Nouvelle recette',
    header_profile: 'Mon profil',
    settings_title: 'Paramètres',
    settings_appearance: 'Apparence',
    settings_language: 'Langue',
    settings_change_language: 'Changer la langue',
    settings_account: 'Compte',
    settings_view_profile: 'Voir mon profil',
    settings_theme: 'Thème',
    settings_theme_description: 'Choisissez votre thème préféré',
    settings_color_scheme: 'Schéma de couleurs',
    settings_color_scheme_description: 'Personnalisez l\'apparence de l\'app',
    settings_profile_description: 'Gérez votre profil et vos recettes',
    settings_about: 'À propos',
    settings_version: 'Version',
    theme_system: 'Système',
    theme_light: 'Clair',
    theme_dark: 'Sombre',
    search_placeholder: 'Rechercher des recettes...',
    search_suggestions: 'Suggestions',
    home_hero_title: 'Cuisino',
    home_hero_sub: 'Partage tes recettes comme sur Instagram, pensée pour la cuisine.',
    chips_all: 'Tous',
    chips_dessert: 'Dessert',
    chips_breakfast: 'Petit-déj',
    chips_italian: 'Italien',
    chips_vegan: 'Vegan',
    chips_drinks: 'Boissons',
    chips_fast: 'Rapide',
    empty_no_recipes: 'Aucune recette trouvée',
    empty_hint_search: "Ajuste ta recherche ou explore d'autres catégories",
    empty_hint_default: 'Tire pour rafraîchir ou ajoute ta première recette !',
    ingredients: 'Ingrédients',
    presentation: 'Présentation',
    steps: 'Étapes',
    share: 'Partager',
    likes: 'likes',
    servings: 'pers.',
    minutes: 'min',
    just_now: 'À l\'instant',
    h: 'h',
    d: 'j',
    w: 's',
    profile_recipes: 'Recettes',
    profile_likes: 'Likes',
    profile_saved: 'Enregistrées',
    profile_edit: 'Éditer le profil',
    profile_add_first: 'Ajouter ma première recette',
    add_title: 'Titre de la recette',
    add_title_ph: 'Entrer un titre...',
    add_desc: 'Description',
    add_desc_ph: 'Décris ta recette...',
    add_ingredients: 'Ingrédients',
    add_instructions: 'Étapes',
    add_step: 'Étape',
    add_publish: 'Publier la recette',
    add_publishing: 'Publication...',
    alert_error: 'Erreur',
    alert_ok: 'OK',
    alert_success: 'Succès ! 🎉',
    alert_published: 'Ta recette a été publiée !',
    pick_tap_photo: 'Appuie pour ajouter une photo',
  },
  en: {
    tabs_home: 'Home',
    tabs_add: 'Add',
    tabs_profile: 'Profile',
    header_home: 'Cuisino',
    header_add: 'New Recipe',
    header_profile: 'My Profile',
    settings_title: 'Settings',
    settings_appearance: 'Appearance',
    settings_language: 'Language',
    settings_change_language: 'Change language',
    settings_account: 'Account',
    settings_view_profile: 'View my profile',
    theme_system: 'System',
    theme_light: 'Light',
    theme_dark: 'Dark',
    search_placeholder: 'Search recipes...',
    home_hero_title: 'Cuisino',
    home_hero_sub: 'Share recipes like Instagram, designed for cooking.',
    chips_all: 'All',
    chips_dessert: 'Dessert',
    chips_breakfast: 'Breakfast',
    chips_italian: 'Italian',
    chips_vegan: 'Vegan',
    chips_drinks: 'Drinks',
    chips_fast: 'Quick',
    empty_no_recipes: 'No recipes found',
    empty_hint_search: 'Adjust your search or explore other categories',
    empty_hint_default: 'Pull to refresh or add your first recipe!',
    ingredients: 'Ingredients',
    presentation: 'Overview',
    steps: 'Steps',
    share: 'Share',
    likes: 'likes',
    servings: 'servings',
    minutes: 'min',
    just_now: 'Just now',
    h: 'h',
    d: 'd',
    w: 'w',
    profile_recipes: 'Recipes',
    profile_likes: 'Likes',
    profile_saved: 'Saved',
    profile_edit: 'Edit Profile',
    profile_add_first: 'Add Your First Recipe',
    add_title: 'Recipe Title',
    add_title_ph: 'Enter recipe title...',
    add_desc: 'Description',
    add_desc_ph: 'Describe your recipe...',
    add_ingredients: 'Ingredients',
    add_instructions: 'Instructions',
    add_step: 'Step',
    add_publish: 'Publish Recipe',
    add_publishing: 'Publishing...',
    alert_error: 'Error',
    alert_ok: 'OK',
    alert_success: 'Success! 🎉',
    alert_published: 'Your recipe has been published!',
    pick_tap_photo: 'Tap to add photo',
  },
  de: {
    tabs_home: 'Start',
    tabs_add: 'Neu',
    tabs_profile: 'Profil',
    header_home: 'Cuisino',
    header_add: 'Neues Rezept',
    header_profile: 'Mein Profil',
    settings_title: 'Einstellungen',
    settings_appearance: 'Darstellung',
    settings_language: 'Sprache',
    settings_change_language: 'Sprache ändern',
    settings_account: 'Konto',
    settings_view_profile: 'Profil anzeigen',
    theme_system: 'System',
    theme_light: 'Hell',
    theme_dark: 'Dunkel',
    search_placeholder: 'Rezepte suchen...',
    home_hero_title: 'Cuisino',
    home_hero_sub: 'Teile Rezepte wie auf Instagram – fürs Kochen gedacht.',
    chips_all: 'Alle',
    chips_dessert: 'Dessert',
    chips_breakfast: 'Frühstück',
    chips_italian: 'Italienisch',
    chips_vegan: 'Vegan',
    chips_drinks: 'Getränke',
    chips_fast: 'Schnell',
    empty_no_recipes: 'Keine Rezepte gefunden',
    empty_hint_search: 'Suche anpassen oder andere Kategorien ansehen',
    empty_hint_default: 'Zum Aktualisieren ziehen oder erstes Rezept hinzufügen!',
    ingredients: 'Zutaten',
    presentation: 'Übersicht',
    steps: 'Schritte',
    share: 'Teilen',
    likes: 'Likes',
    servings: 'Portionen',
    minutes: 'Min',
    just_now: 'Gerade eben',
    h: 'Std',
    d: 'Tg',
    w: 'Wo',
    profile_recipes: 'Rezepte',
    profile_likes: 'Likes',
    profile_saved: 'Gespeichert',
    profile_edit: 'Profil bearbeiten',
    profile_add_first: 'Erstes Rezept hinzufügen',
    add_title: 'Rezepttitel',
    add_title_ph: 'Rezepttitel eingeben...',
    add_desc: 'Beschreibung',
    add_desc_ph: 'Beschreibe dein Rezept...',
    add_ingredients: 'Zutaten',
    add_instructions: 'Anleitung',
    add_step: 'Schritt',
    add_publish: 'Rezept veröffentlichen',
    add_publishing: 'Veröffentliche...',
    alert_error: 'Fehler',
    alert_ok: 'OK',
    alert_success: 'Erfolg! 🎉',
    alert_published: 'Dein Rezept wurde veröffentlicht!',
    pick_tap_photo: 'Zum Hinzufügen tippen',
  },
  zh: {
    tabs_home: '首页',
    tabs_add: '发布',
    tabs_profile: '个人',
    header_home: 'Cuisino',
    header_add: '新食谱',
    header_profile: '我的资料',
    settings_title: '设置',
    settings_appearance: '外观',
    settings_language: '语言',
    settings_change_language: '更改语言',
    settings_account: '账户',
    settings_view_profile: '查看我的资料',
    theme_system: '系统',
    theme_light: '浅色',
    theme_dark: '深色',
    search_placeholder: '搜索食谱...',
    home_hero_title: 'Cuisino',
    home_hero_sub: '像 Instagram 一样分享食谱，更适合烹饪。',
    chips_all: '全部',
    chips_dessert: '甜点',
    chips_breakfast: '早餐',
    chips_italian: '意式',
    chips_vegan: '纯素',
    chips_drinks: '饮品',
    chips_fast: '快速',
    empty_no_recipes: '未找到食谱',
    empty_hint_search: '调整搜索或浏览其他分类',
    empty_hint_default: '下拉刷新或添加你的第一道菜！',
    ingredients: '配料',
    presentation: '介绍',
    steps: '步骤',
    share: '分享',
    likes: '喜欢',
    servings: '人份',
    minutes: '分钟',
    just_now: '刚刚',
    h: '小时',
    d: '天',
    w: '周',
    profile_recipes: '食谱',
    profile_likes: '喜欢',
    profile_saved: '已保存',
    profile_edit: '编辑资料',
    profile_add_first: '添加我的第一个食谱',
    add_title: '菜谱标题',
    add_title_ph: '输入标题...',
    add_desc: '描述',
    add_desc_ph: '描述你的菜谱...',
    add_ingredients: '配料',
    add_instructions: '步骤',
    add_step: '步骤',
    add_publish: '发布菜谱',
    add_publishing: '发布中...',
    alert_error: '错误',
    alert_ok: '确定',
    alert_success: '成功！🎉',
    alert_published: '你的菜谱已发布！',
    pick_tap_photo: '点击添加照片',
  },
  ja: {
    tabs_home: 'ホーム',
    tabs_add: '投稿',
    tabs_profile: 'プロフィール',
    header_home: 'Cuisino',
    header_add: '新規レシピ',
    header_profile: 'マイプロフィール',
    settings_title: '設定',
    settings_appearance: '外観',
    settings_language: '言語',
    settings_change_language: '言語を変更',
    settings_account: 'アカウント',
    settings_view_profile: 'プロフィールを見る',
    theme_system: 'システム',
    theme_light: 'ライト',
    theme_dark: 'ダーク',
    search_placeholder: 'レシピを検索...',
    home_hero_title: 'Cuisino',
    home_hero_sub: 'Instagramのようにレシピを共有、料理に最適。',
    chips_all: 'すべて',
    chips_dessert: 'デザート',
    chips_breakfast: '朝食',
    chips_italian: 'イタリアン',
    chips_vegan: 'ビーガン',
    chips_drinks: 'ドリンク',
    chips_fast: '時短',
    empty_no_recipes: 'レシピが見つかりません',
    empty_hint_search: '検索を調整するか他のカテゴリを探す',
    empty_hint_default: '引っ張って更新、または最初のレシピを追加！',
    ingredients: '材料',
    presentation: '概要',
    steps: '手順',
    share: '共有',
    likes: 'いいね',
    servings: '人分',
    minutes: '分',
    just_now: 'たった今',
    h: '時間',
    d: '日',
    w: '週',
    profile_recipes: 'レシピ',
    profile_likes: 'いいね',
    profile_saved: '保存済み',
    profile_edit: 'プロフィールを編集',
    profile_add_first: '最初のレシピを追加',
    add_title: 'レシピ名',
    add_title_ph: 'タイトルを入力...',
    add_desc: '説明',
    add_desc_ph: 'レシピを説明...',
    add_ingredients: '材料',
    add_instructions: '手順',
    add_step: '手順',
    add_publish: 'レシピを投稿',
    add_publishing: '投稿中...',
    alert_error: 'エラー',
    alert_ok: 'OK',
    alert_success: '成功！🎉',
    alert_published: 'レシピを公開しました！',
    pick_tap_photo: 'タップして写真を追加',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('fr');

  useEffect(() => {
    (async () => {
      const saved = await AsyncStorage.getItem(STORAGE_KEY);
      if (saved === 'fr' || saved === 'en' || saved === 'de' || saved === 'zh' || saved === 'ja') {
        setLocaleState(saved);
      }
    })();
  }, []);

  const setLocale = async (l: Locale) => {
    setLocaleState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l);
  };

  const t = (key: string) => STRINGS[locale][key] ?? key;

  const value: LanguageContextValue = useMemo(() => ({ locale, setLocale, t }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
} 